rm dwi_data*
rm products.json
rm sca-autoalignacpc*
rm finished
rm jobid
rm t1_acpc_aligned.nii.gz
rm sca-alignacpc.*
#rm finished
#rm jobid*
#rm final_jobid
#rm jq
#rm response.txt
#rm *.mif
#rm grad.b
#rm *.tck
#rm products.json
#rm wm.nii.gz
#rm figure*.png
#rm life_fascicle_weights.json
#rm life_error.json
#rm life_results.json
#rm output_fe.mat
